name: Andy Kitchen
favicon: null
layout_spectrum: 0.50319
typography_spectrum: 0.56617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e27902'
    - '#929292'
    - '#950900'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
