name: Andy Kitchen
favicon: null
layout_spectrum: 0.15188491181470454
typography_spectrum: 0.56617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9670180447865278
  lightness: 0.2907460820861161
  saturation: 0.9793182942084968
  rhythmicContrast: 0.9959175975527614
purpose: []
